### ISSUE TITLE
"'luaL_newlib' was not declared in this scope" when installing via luarocks

### ISSUE THREAD

**Issue by 11clock** [pigpigyyy/Yuescript#70]
Below is the output from the terminal.

PS C:\Users\justi\Documents\DefoldProjects\chess-parent\3-chess-client-love> luarocks install yuescript
Installing https://luarocks.org/yuescript-0.9.0-1.src.rock

yuescript 0.9.0-1 depends on lua >= 5.1 (5.1-1 provided by VM)
-- The CXX compiler identification is GNU 8.1.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Lua: C:/Program Files (x86)/LuaRocks/lua51.lib (found version "5.1.5") 
-- Lua: C:\Program Files (x86)\LuaRocks/lua5.1
-- Lua include: C:/Program Files (x86)/LuaRocks/include  
-- Lua library: C:/Program Files (x86)/LuaRocks/lua51.lib
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
[  7%] Building CXX object CMakeFiles/libyue.dir/src/yuescript/ast.cpp.obj
[ 15%] Building CXX object CMakeFiles/libyue.dir/src/yuescript/parser.cpp.obj
[ 23%] Building CXX object CMakeFiles/libyue.dir/src/yuescript/yue_parser.cpp.obj
[ 30%] Building CXX object CMakeFiles/libyue.dir/src/yuescript/yue_compiler.cpp.obj
[ 38%] Building CXX object CMakeFiles/libyue.dir/src/yuescript/yuescript.cpp.obj
C:\Users\justi\AppData\Local\Temp\luarocks_yuescript-0.9.0-1-2702\yuescript\src\yuescript\yuescript.cpp: In function 'int luaopen_yue(lua_State*)':
C:\Users\justi\AppData\Local\Temp\luarocks_yuescript-0.9.0-1-2702\yuescript\src\yuescript\yuescript.cpp:136:2: error: 'luaL_newlib' was not declared in this scope
  luaL_newlib(L, yuelib); // yue
  ^~~~~~~~~~~
C:\Users\justi\AppData\Local\Temp\luarocks_yuescript-0.9.0-1-2702\yuescript\src\yuescript\yuescript.cpp:136:2: note: suggested alternative: 'luaL_openlib'
  luaL_newlib(L, yuelib); // yue
  ^~~~~~~~~~~
  luaL_openlib
mingw32-make.exe[2]: *** [CMakeFiles\libyue.dir\build.make:136: CMakeFiles/libyue.dir/src/yuescript/yuescript.cpp.obj] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:84: CMakeFiles/libyue.dir/all] Error 2
mingw32-make.exe: *** [Makefile:135: all] Error 2

Error: Build error: Failed building.

**Comment by pigpigyyy** [comment]
Thanks, forgot to test build with Lua 5.1. Should be fixed by commit 8953ecec306536cd0b18c9de316461ad4c35166f and you may now try again with luarocks.
